### ISSUE TITLE
Multiple Intent for lists which doesn't have a parent causes error, and doesn't render output.  

### ISSUE THREAD

**Issue by muadpn** [mdx-editor/editor#303] opened 2024-01-13 17:05 UTC
Soo basically I was testing out this library for a blog application, and 
if i add a list and press enter, and press tab multiple time to create a list without node. this gives error.

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'children')
Call Stack
isParent
node_modules\@mdxeditor\editor\dist\exportMarkdownFromLexical.js (6:0)
appendToParent
node_modules\@mdxeditor\editor\dist\exportMarkdownFromLexical.js (27:0)
Object.addAndStepInto
node_modules\@mdxeditor\editor\dist\exportMarkdownFromLexical.js (72:0)
Object.visitLexicalNode
node_modules\@mdxeditor\editor\dist\plugins\lists\LexicalListVisitor.js (5:0)

its okay to get a error, but how to handle it ?, I have test this same on the live demo which MDxEditor providers application and it also contain the same error on console.
![Picture2](https://github.com/mdx-editor/editor/assets/14163394/ca7e731d-7be2-45d8-8a23-8146f4994bee)
![Pictyure1](https://github.com/mdx-editor/editor/assets/14163394/12119dbf-2885-4b91-bf76-1ccfc8590b1c)

**Comment by petyosi** [comment] 2024-01-13 19:05
Duplicate of https://github.com/mdx-editor/editor/issues/178. Super hard to fix, I think I will probably just prevent it...

**Closed** 2024-01-13 19:05 UTC

**Comment by bloodteller123** [comment] 2024-06-07 15:07
> Duplicate of #178. Super hard to fix, I think I will probably just prevent it...

Thanks for your time, just curious, is there any config that we can set to prevent this nested list?
