### ISSUE TITLE
[BUG] Crash when pasting nested list of richtext

### ISSUE THREAD

**Issue by TomNUSDS** [mdx-editor/editor#498] opened 2024-06-18 21:44 UTC
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
Pasting nested lists into the richtext editor causes an exception.

**To Reproduce**
1. Go to [MDX Editor Live demo site](https://mdxeditor.dev/editor/demo)
2. Clear the content in the richtext editor so it's empty
3. Open browser debugger to watch for crash
4. Extract attached richtext example data from `test.rtf.zip`
5. Open test.rtf with any editor that supports richtext
6. Copy content and paste into the MDXEditor richtext area.
Result: crashes
`Uncaught TypeError: Cannot read properties of undefined (reading 'children')
    at h `
Note: Switching to Markdown view in MDXEditor shows empty content.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
The code is minimized, but I think it's in `isParent()` when the `node` parameter is null for some reason.

[test.rtf.zip](https://github.com/user-attachments/files/15892958/test.rtf.zip)

**Comment by petyosi** [comment] 2024-06-19 04:46
This is a duplicate of https://github.com/mdx-editor/editor/issues/178

**Closed by petyosi** 2024-06-19 04:46 UTC
Labels: bug

**Comment by TomNUSDS** [comment] 2024-06-20 14:37
Sorry for the duplicate. I did search through the issues, must of just missed it.
